version: "3.3"

services:
  api:
    build: .
    container_name: api
    ports:
      - 4444:8080
  server:
    image: server
    container_name: frontend
    ports:
      - 80:8080
  database:
    image: mariadb
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marketapp
